version: "3.8"
services:
  app:
    hostname: app
    restart: always
    image: "node:14"
    working_dir: /home/node/app
    environment:
      SESSION_SECRET_KEY: 9246f37d0faa30d65744463743ca1ade
      NODE_ENV: production
      DATABASE_UR: mongodb://localhost:27017/aave?replicaSet=rs0
      POLYGON_RPC: <polygon rpc>
      MAINNET_RPC: <mainnet rpc>
      PORT: 3004
    volumes:
      - ./:/home/node/app
    command: npm run start
    network_mode: host
  #liquidator:
  #  restart: always
  #  depends_on:
  #    - app
  #  image: "node:14"
  #  working_dir: /home/node/app
  #  volumes:
  #    - ../liquidationbot:/home/node/app
  #  command: npm run dev
  #  network_mode: host
  #  environment:
  #    PORT: 3004
