version: "3.8"
services:
  app:
    hostname: app
    restart: always
    image: "ghcr.io/sakulstra/info.aave:main"
    environment:
      SESSION_SECRET_KEY: 9246f37d0faa30d65744463743ca1ade
      NODE_ENV: production
      DATABASE_URL: mongodb://localhost:27017/aave?replicaSet=rs0
      POLYGON_RPC: <polgon rpc>
      MAINNET_RPC: <mainnet rpc>
      PORT: 3004
