module.exports = {
  scalars: [0, 1, 3, 4, 7, 8, 9, 10, 14, 18, 21, 23, 24, 28, 31],
  types: {
    BigDecimal: {},
    BigInt: {},
    Block_height: {
      hash: [4],
      number: [9],
      __typename: [24],
    },
    Boolean: {},
    Bytes: {},
    ClaimReward: {
      id: [8],
      stakeToken: [19],
      from: [24],
      to: [24],
      amount: [1],
      stakePosition: [16],
      __typename: [24],
    },
    ClaimReward_filter: {
      id: [8],
      id_not: [8],
      id_gt: [8],
      id_lt: [8],
      id_gte: [8],
      id_lte: [8],
      id_in: [8],
      id_not_in: [8],
      stakeToken: [24],
      stakeToken_not: [24],
      stakeToken_gt: [24],
      stakeToken_lt: [24],
      stakeToken_gte: [24],
      stakeToken_lte: [24],
      stakeToken_in: [24],
      stakeToken_not_in: [24],
      stakeToken_contains: [24],
      stakeToken_not_contains: [24],
      stakeToken_starts_with: [24],
      stakeToken_not_starts_with: [24],
      stakeToken_ends_with: [24],
      stakeToken_not_ends_with: [24],
      from: [24],
      from_not: [24],
      from_gt: [24],
      from_lt: [24],
      from_gte: [24],
      from_lte: [24],
      from_in: [24],
      from_not_in: [24],
      from_contains: [24],
      from_not_contains: [24],
      from_starts_with: [24],
      from_not_starts_with: [24],
      from_ends_with: [24],
      from_not_ends_with: [24],
      to: [24],
      to_not: [24],
      to_gt: [24],
      to_lt: [24],
      to_gte: [24],
      to_lte: [24],
      to_in: [24],
      to_not_in: [24],
      to_contains: [24],
      to_not_contains: [24],
      to_starts_with: [24],
      to_not_starts_with: [24],
      to_ends_with: [24],
      to_not_ends_with: [24],
      amount: [1],
      amount_not: [1],
      amount_gt: [1],
      amount_lt: [1],
      amount_gte: [1],
      amount_lte: [1],
      amount_in: [1],
      amount_not_in: [1],
      stakePosition: [24],
      stakePosition_not: [24],
      stakePosition_gt: [24],
      stakePosition_lt: [24],
      stakePosition_gte: [24],
      stakePosition_lte: [24],
      stakePosition_in: [24],
      stakePosition_not_in: [24],
      stakePosition_contains: [24],
      stakePosition_not_contains: [24],
      stakePosition_starts_with: [24],
      stakePosition_not_starts_with: [24],
      stakePosition_ends_with: [24],
      stakePosition_not_ends_with: [24],
      __typename: [24],
    },
    ClaimReward_orderBy: {},
    ID: {},
    Int: {},
    OrderDirection: {},
    Query: {
      stake: [
        15,
        {
          id: [8, "ID!"],
          block: [2],
        },
      ],
      stakes: [
        15,
        {
          skip: [9],
          first: [9],
          orderBy: [23],
          orderDirection: [10],
          where: [22],
          block: [2],
        },
      ],
      redeem: [
        12,
        {
          id: [8, "ID!"],
          block: [2],
        },
      ],
      redeems: [
        12,
        {
          skip: [9],
          first: [9],
          orderBy: [14],
          orderDirection: [10],
          where: [13],
          block: [2],
        },
      ],
      claimReward: [
        5,
        {
          id: [8, "ID!"],
          block: [2],
        },
      ],
      claimRewards: [
        5,
        {
          skip: [9],
          first: [9],
          orderBy: [7],
          orderDirection: [10],
          where: [6],
          block: [2],
        },
      ],
      transfer: [
        26,
        {
          id: [8, "ID!"],
          block: [2],
        },
      ],
      transfers: [
        26,
        {
          skip: [9],
          first: [9],
          orderBy: [28],
          orderDirection: [10],
          where: [27],
          block: [2],
        },
      ],
      stakePosition: [
        16,
        {
          id: [8, "ID!"],
          block: [2],
        },
      ],
      stakePositions: [
        16,
        {
          skip: [9],
          first: [9],
          orderBy: [18],
          orderDirection: [10],
          where: [17],
          block: [2],
        },
      ],
      stakeToken: [
        19,
        {
          id: [8, "ID!"],
          block: [2],
        },
      ],
      stakeTokens: [
        19,
        {
          skip: [9],
          first: [9],
          orderBy: [21],
          orderDirection: [10],
          where: [20],
          block: [2],
        },
      ],
      _meta: [
        30,
        {
          block: [2],
        },
      ],
      __typename: [24],
    },
    Redeem: {
      id: [8],
      stakeToken: [19],
      from: [24],
      to: [24],
      amount: [1],
      stakePosition: [16],
      __typename: [24],
    },
    Redeem_filter: {
      id: [8],
      id_not: [8],
      id_gt: [8],
      id_lt: [8],
      id_gte: [8],
      id_lte: [8],
      id_in: [8],
      id_not_in: [8],
      stakeToken: [24],
      stakeToken_not: [24],
      stakeToken_gt: [24],
      stakeToken_lt: [24],
      stakeToken_gte: [24],
      stakeToken_lte: [24],
      stakeToken_in: [24],
      stakeToken_not_in: [24],
      stakeToken_contains: [24],
      stakeToken_not_contains: [24],
      stakeToken_starts_with: [24],
      stakeToken_not_starts_with: [24],
      stakeToken_ends_with: [24],
      stakeToken_not_ends_with: [24],
      from: [24],
      from_not: [24],
      from_gt: [24],
      from_lt: [24],
      from_gte: [24],
      from_lte: [24],
      from_in: [24],
      from_not_in: [24],
      from_contains: [24],
      from_not_contains: [24],
      from_starts_with: [24],
      from_not_starts_with: [24],
      from_ends_with: [24],
      from_not_ends_with: [24],
      to: [24],
      to_not: [24],
      to_gt: [24],
      to_lt: [24],
      to_gte: [24],
      to_lte: [24],
      to_in: [24],
      to_not_in: [24],
      to_contains: [24],
      to_not_contains: [24],
      to_starts_with: [24],
      to_not_starts_with: [24],
      to_ends_with: [24],
      to_not_ends_with: [24],
      amount: [1],
      amount_not: [1],
      amount_gt: [1],
      amount_lt: [1],
      amount_gte: [1],
      amount_lte: [1],
      amount_in: [1],
      amount_not_in: [1],
      stakePosition: [24],
      stakePosition_not: [24],
      stakePosition_gt: [24],
      stakePosition_lt: [24],
      stakePosition_gte: [24],
      stakePosition_lte: [24],
      stakePosition_in: [24],
      stakePosition_not_in: [24],
      stakePosition_contains: [24],
      stakePosition_not_contains: [24],
      stakePosition_starts_with: [24],
      stakePosition_not_starts_with: [24],
      stakePosition_ends_with: [24],
      stakePosition_not_ends_with: [24],
      __typename: [24],
    },
    Redeem_orderBy: {},
    Stake: {
      id: [8],
      stakeToken: [19],
      from: [24],
      onBehalfOf: [24],
      amount: [1],
      stakePosition: [16],
      __typename: [24],
    },
    StakePosition: {
      id: [8],
      positionBalance: [1],
      rewardsClaimed: [1],
      user: [24],
      stakeToken: [19],
      stakeHistory: [
        15,
        {
          skip: [9],
          first: [9],
          orderBy: [23],
          orderDirection: [10],
          where: [22],
        },
      ],
      redeemHistory: [
        12,
        {
          skip: [9],
          first: [9],
          orderBy: [14],
          orderDirection: [10],
          where: [13],
        },
      ],
      transferHistory: [
        26,
        {
          skip: [9],
          first: [9],
          orderBy: [28],
          orderDirection: [10],
          where: [27],
        },
      ],
      __typename: [24],
    },
    StakePosition_filter: {
      id: [8],
      id_not: [8],
      id_gt: [8],
      id_lt: [8],
      id_gte: [8],
      id_lte: [8],
      id_in: [8],
      id_not_in: [8],
      positionBalance: [1],
      positionBalance_not: [1],
      positionBalance_gt: [1],
      positionBalance_lt: [1],
      positionBalance_gte: [1],
      positionBalance_lte: [1],
      positionBalance_in: [1],
      positionBalance_not_in: [1],
      rewardsClaimed: [1],
      rewardsClaimed_not: [1],
      rewardsClaimed_gt: [1],
      rewardsClaimed_lt: [1],
      rewardsClaimed_gte: [1],
      rewardsClaimed_lte: [1],
      rewardsClaimed_in: [1],
      rewardsClaimed_not_in: [1],
      user: [24],
      user_not: [24],
      user_gt: [24],
      user_lt: [24],
      user_gte: [24],
      user_lte: [24],
      user_in: [24],
      user_not_in: [24],
      user_contains: [24],
      user_not_contains: [24],
      user_starts_with: [24],
      user_not_starts_with: [24],
      user_ends_with: [24],
      user_not_ends_with: [24],
      stakeToken: [24],
      stakeToken_not: [24],
      stakeToken_gt: [24],
      stakeToken_lt: [24],
      stakeToken_gte: [24],
      stakeToken_lte: [24],
      stakeToken_in: [24],
      stakeToken_not_in: [24],
      stakeToken_contains: [24],
      stakeToken_not_contains: [24],
      stakeToken_starts_with: [24],
      stakeToken_not_starts_with: [24],
      stakeToken_ends_with: [24],
      stakeToken_not_ends_with: [24],
      __typename: [24],
    },
    StakePosition_orderBy: {},
    StakeToken: {
      id: [8],
      stakedToken: [24],
      rewardToken: [24],
      name: [24],
      symbol: [24],
      decimals: [9],
      cooldownSeconds: [1],
      unstakeWindow: [1],
      currentStakedBalance: [1],
      lifetimeRewardsDistributed: [1],
      lifetimeStakedBalance: [1],
      lifetimeRedeemedBalance: [1],
      stakeHistory: [
        15,
        {
          skip: [9],
          first: [9],
          orderBy: [23],
          orderDirection: [10],
          where: [22],
        },
      ],
      redeemHistory: [
        12,
        {
          skip: [9],
          first: [9],
          orderBy: [14],
          orderDirection: [10],
          where: [13],
        },
      ],
      transferHistory: [
        26,
        {
          skip: [9],
          first: [9],
          orderBy: [28],
          orderDirection: [10],
          where: [27],
        },
      ],
      stakePositions: [
        16,
        {
          skip: [9],
          first: [9],
          orderBy: [18],
          orderDirection: [10],
          where: [17],
        },
      ],
      __typename: [24],
    },
    StakeToken_filter: {
      id: [8],
      id_not: [8],
      id_gt: [8],
      id_lt: [8],
      id_gte: [8],
      id_lte: [8],
      id_in: [8],
      id_not_in: [8],
      stakedToken: [24],
      stakedToken_not: [24],
      stakedToken_gt: [24],
      stakedToken_lt: [24],
      stakedToken_gte: [24],
      stakedToken_lte: [24],
      stakedToken_in: [24],
      stakedToken_not_in: [24],
      stakedToken_contains: [24],
      stakedToken_not_contains: [24],
      stakedToken_starts_with: [24],
      stakedToken_not_starts_with: [24],
      stakedToken_ends_with: [24],
      stakedToken_not_ends_with: [24],
      rewardToken: [24],
      rewardToken_not: [24],
      rewardToken_gt: [24],
      rewardToken_lt: [24],
      rewardToken_gte: [24],
      rewardToken_lte: [24],
      rewardToken_in: [24],
      rewardToken_not_in: [24],
      rewardToken_contains: [24],
      rewardToken_not_contains: [24],
      rewardToken_starts_with: [24],
      rewardToken_not_starts_with: [24],
      rewardToken_ends_with: [24],
      rewardToken_not_ends_with: [24],
      name: [24],
      name_not: [24],
      name_gt: [24],
      name_lt: [24],
      name_gte: [24],
      name_lte: [24],
      name_in: [24],
      name_not_in: [24],
      name_contains: [24],
      name_not_contains: [24],
      name_starts_with: [24],
      name_not_starts_with: [24],
      name_ends_with: [24],
      name_not_ends_with: [24],
      symbol: [24],
      symbol_not: [24],
      symbol_gt: [24],
      symbol_lt: [24],
      symbol_gte: [24],
      symbol_lte: [24],
      symbol_in: [24],
      symbol_not_in: [24],
      symbol_contains: [24],
      symbol_not_contains: [24],
      symbol_starts_with: [24],
      symbol_not_starts_with: [24],
      symbol_ends_with: [24],
      symbol_not_ends_with: [24],
      decimals: [9],
      decimals_not: [9],
      decimals_gt: [9],
      decimals_lt: [9],
      decimals_gte: [9],
      decimals_lte: [9],
      decimals_in: [9],
      decimals_not_in: [9],
      cooldownSeconds: [1],
      cooldownSeconds_not: [1],
      cooldownSeconds_gt: [1],
      cooldownSeconds_lt: [1],
      cooldownSeconds_gte: [1],
      cooldownSeconds_lte: [1],
      cooldownSeconds_in: [1],
      cooldownSeconds_not_in: [1],
      unstakeWindow: [1],
      unstakeWindow_not: [1],
      unstakeWindow_gt: [1],
      unstakeWindow_lt: [1],
      unstakeWindow_gte: [1],
      unstakeWindow_lte: [1],
      unstakeWindow_in: [1],
      unstakeWindow_not_in: [1],
      currentStakedBalance: [1],
      currentStakedBalance_not: [1],
      currentStakedBalance_gt: [1],
      currentStakedBalance_lt: [1],
      currentStakedBalance_gte: [1],
      currentStakedBalance_lte: [1],
      currentStakedBalance_in: [1],
      currentStakedBalance_not_in: [1],
      lifetimeRewardsDistributed: [1],
      lifetimeRewardsDistributed_not: [1],
      lifetimeRewardsDistributed_gt: [1],
      lifetimeRewardsDistributed_lt: [1],
      lifetimeRewardsDistributed_gte: [1],
      lifetimeRewardsDistributed_lte: [1],
      lifetimeRewardsDistributed_in: [1],
      lifetimeRewardsDistributed_not_in: [1],
      lifetimeStakedBalance: [1],
      lifetimeStakedBalance_not: [1],
      lifetimeStakedBalance_gt: [1],
      lifetimeStakedBalance_lt: [1],
      lifetimeStakedBalance_gte: [1],
      lifetimeStakedBalance_lte: [1],
      lifetimeStakedBalance_in: [1],
      lifetimeStakedBalance_not_in: [1],
      lifetimeRedeemedBalance: [1],
      lifetimeRedeemedBalance_not: [1],
      lifetimeRedeemedBalance_gt: [1],
      lifetimeRedeemedBalance_lt: [1],
      lifetimeRedeemedBalance_gte: [1],
      lifetimeRedeemedBalance_lte: [1],
      lifetimeRedeemedBalance_in: [1],
      lifetimeRedeemedBalance_not_in: [1],
      __typename: [24],
    },
    StakeToken_orderBy: {},
    Stake_filter: {
      id: [8],
      id_not: [8],
      id_gt: [8],
      id_lt: [8],
      id_gte: [8],
      id_lte: [8],
      id_in: [8],
      id_not_in: [8],
      stakeToken: [24],
      stakeToken_not: [24],
      stakeToken_gt: [24],
      stakeToken_lt: [24],
      stakeToken_gte: [24],
      stakeToken_lte: [24],
      stakeToken_in: [24],
      stakeToken_not_in: [24],
      stakeToken_contains: [24],
      stakeToken_not_contains: [24],
      stakeToken_starts_with: [24],
      stakeToken_not_starts_with: [24],
      stakeToken_ends_with: [24],
      stakeToken_not_ends_with: [24],
      from: [24],
      from_not: [24],
      from_gt: [24],
      from_lt: [24],
      from_gte: [24],
      from_lte: [24],
      from_in: [24],
      from_not_in: [24],
      from_contains: [24],
      from_not_contains: [24],
      from_starts_with: [24],
      from_not_starts_with: [24],
      from_ends_with: [24],
      from_not_ends_with: [24],
      onBehalfOf: [24],
      onBehalfOf_not: [24],
      onBehalfOf_gt: [24],
      onBehalfOf_lt: [24],
      onBehalfOf_gte: [24],
      onBehalfOf_lte: [24],
      onBehalfOf_in: [24],
      onBehalfOf_not_in: [24],
      onBehalfOf_contains: [24],
      onBehalfOf_not_contains: [24],
      onBehalfOf_starts_with: [24],
      onBehalfOf_not_starts_with: [24],
      onBehalfOf_ends_with: [24],
      onBehalfOf_not_ends_with: [24],
      amount: [1],
      amount_not: [1],
      amount_gt: [1],
      amount_lt: [1],
      amount_gte: [1],
      amount_lte: [1],
      amount_in: [1],
      amount_not_in: [1],
      stakePosition: [24],
      stakePosition_not: [24],
      stakePosition_gt: [24],
      stakePosition_lt: [24],
      stakePosition_gte: [24],
      stakePosition_lte: [24],
      stakePosition_in: [24],
      stakePosition_not_in: [24],
      stakePosition_contains: [24],
      stakePosition_not_contains: [24],
      stakePosition_starts_with: [24],
      stakePosition_not_starts_with: [24],
      stakePosition_ends_with: [24],
      stakePosition_not_ends_with: [24],
      __typename: [24],
    },
    Stake_orderBy: {},
    String: {},
    Subscription: {
      stake: [
        15,
        {
          id: [8, "ID!"],
          block: [2],
        },
      ],
      stakes: [
        15,
        {
          skip: [9],
          first: [9],
          orderBy: [23],
          orderDirection: [10],
          where: [22],
          block: [2],
        },
      ],
      redeem: [
        12,
        {
          id: [8, "ID!"],
          block: [2],
        },
      ],
      redeems: [
        12,
        {
          skip: [9],
          first: [9],
          orderBy: [14],
          orderDirection: [10],
          where: [13],
          block: [2],
        },
      ],
      claimReward: [
        5,
        {
          id: [8, "ID!"],
          block: [2],
        },
      ],
      claimRewards: [
        5,
        {
          skip: [9],
          first: [9],
          orderBy: [7],
          orderDirection: [10],
          where: [6],
          block: [2],
        },
      ],
      transfer: [
        26,
        {
          id: [8, "ID!"],
          block: [2],
        },
      ],
      transfers: [
        26,
        {
          skip: [9],
          first: [9],
          orderBy: [28],
          orderDirection: [10],
          where: [27],
          block: [2],
        },
      ],
      stakePosition: [
        16,
        {
          id: [8, "ID!"],
          block: [2],
        },
      ],
      stakePositions: [
        16,
        {
          skip: [9],
          first: [9],
          orderBy: [18],
          orderDirection: [10],
          where: [17],
          block: [2],
        },
      ],
      stakeToken: [
        19,
        {
          id: [8, "ID!"],
          block: [2],
        },
      ],
      stakeTokens: [
        19,
        {
          skip: [9],
          first: [9],
          orderBy: [21],
          orderDirection: [10],
          where: [20],
          block: [2],
        },
      ],
      _meta: [
        30,
        {
          block: [2],
        },
      ],
      __typename: [24],
    },
    Transfer: {
      id: [8],
      stakeToken: [19],
      from: [24],
      to: [24],
      amount: [1],
      stakePosition: [16],
      __typename: [24],
    },
    Transfer_filter: {
      id: [8],
      id_not: [8],
      id_gt: [8],
      id_lt: [8],
      id_gte: [8],
      id_lte: [8],
      id_in: [8],
      id_not_in: [8],
      stakeToken: [24],
      stakeToken_not: [24],
      stakeToken_gt: [24],
      stakeToken_lt: [24],
      stakeToken_gte: [24],
      stakeToken_lte: [24],
      stakeToken_in: [24],
      stakeToken_not_in: [24],
      stakeToken_contains: [24],
      stakeToken_not_contains: [24],
      stakeToken_starts_with: [24],
      stakeToken_not_starts_with: [24],
      stakeToken_ends_with: [24],
      stakeToken_not_ends_with: [24],
      from: [24],
      from_not: [24],
      from_gt: [24],
      from_lt: [24],
      from_gte: [24],
      from_lte: [24],
      from_in: [24],
      from_not_in: [24],
      from_contains: [24],
      from_not_contains: [24],
      from_starts_with: [24],
      from_not_starts_with: [24],
      from_ends_with: [24],
      from_not_ends_with: [24],
      to: [24],
      to_not: [24],
      to_gt: [24],
      to_lt: [24],
      to_gte: [24],
      to_lte: [24],
      to_in: [24],
      to_not_in: [24],
      to_contains: [24],
      to_not_contains: [24],
      to_starts_with: [24],
      to_not_starts_with: [24],
      to_ends_with: [24],
      to_not_ends_with: [24],
      amount: [1],
      amount_not: [1],
      amount_gt: [1],
      amount_lt: [1],
      amount_gte: [1],
      amount_lte: [1],
      amount_in: [1],
      amount_not_in: [1],
      stakePosition: [24],
      stakePosition_not: [24],
      stakePosition_gt: [24],
      stakePosition_lt: [24],
      stakePosition_gte: [24],
      stakePosition_lte: [24],
      stakePosition_in: [24],
      stakePosition_not_in: [24],
      stakePosition_contains: [24],
      stakePosition_not_contains: [24],
      stakePosition_starts_with: [24],
      stakePosition_not_starts_with: [24],
      stakePosition_ends_with: [24],
      stakePosition_not_ends_with: [24],
      __typename: [24],
    },
    Transfer_orderBy: {},
    _Block_: {
      hash: [4],
      number: [9],
      __typename: [24],
    },
    _Meta_: {
      block: [29],
      deployment: [24],
      hasIndexingErrors: [3],
      __typename: [24],
    },
    _SubgraphErrorPolicy_: {},
  },
}
